language: node_js

node_js:
  - "4.1"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - node_modules/gulp/bin/gulp.js
  - node_modules/superstatic/bin/server public --port 8000 --host localhost  > /dev/null &
  - sleep 1 # give server time to start

script:
  - node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots,coverage --browsers=Firefox
  - node_modules/protractor/bin/protractor protractor.conf.js --browser=firefox
